# Generated by Django 3.1.4 on 2021-01-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='author',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='category',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
