# Generated by Django 3.1.4 on 2021-01-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210103_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='content',
            field=models.TextField(default='Unknown'),
        ),
    ]
